apiVersion: k0rdent.mirantis.com/v1beta1
kind: Credential
metadata:
  annotations:
  labels:
    k0rdent.mirantis.com/component: kcm
  name: hcloud-cluster-provisioning
  namespace: kcm-system
spec:
  description: Hetzner Cloud credentials for cluster provisioning
  identityRef:
    apiVersion: v1
    kind: Secret
    name: hcloud-cluster-provisioning-token
    namespace: kcm-system
