apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hetzner-hosted-cp-repo
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  url: oci://ghcr.io/enopax/hetzner-hosted-cp
  type: oci
  interval: 10m
