apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: hetzner-standalone-cp
  namespace: kcm-system
spec:
  helm:
    chartSpec:
      chart: hetzner-standalone-cp
      version: 1.0.11
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: hetzner-standalone-cp-repo

