apiVersion: v1
kind: Secret
metadata:
  name: hcloud-cluster-provisioning-token
  namespace: ${CLUSTER_NAMESPACE}
  labels:
    k0rdent.mirantis.com/component: kcm
type: Opaque
data:
  HCLOUD_TOKEN: ${HETZNER_TOKEN_BASE64}
